(() => {
  const clean={
    'Architectural cleaning and bespoke housekeeping crafted for discerning homeowners, modern offices, and seaside properties across greater Tallinn.':'Professional cleaning for homes, offices and special spaces across Tallinn.',
    'Verified Staff':'Personal coordination','Permanent Tallinn personnel, identity & reference checked.':'We review every request and confirm the details before your visit.',
    'Nordic Ecolabel':'Cleaning supplies included','Hypoallergenic, fragrance-free solutions included by default.':'We bring the essential supplies for standard cleaning.',
    'Direct Protocol':'Clear scope','Personal coordinator review and pre-arrival scheduling.':'Service, date and final price are confirmed before the visit.',
    'Configure Your Plan':'Build your cleaning plan','Regular Care':'Regular cleaning','Deep Sanity Clean':'Deep cleaning','Move-Out / In':'Move-out & renovation','Glazing & Fabrics':'Windows & textiles','Yachts & Marine Salons':'Yachts & marine spaces',
    'Configure your bespoke plan.':'Build your cleaning plan.','Itemized pricing transparently calculated based on square meters, room counts, and custom requirements in Tallinn.':'Choose your service and space details. We show an estimate and personally confirm the final price.',
    'Need a more complex job?':'Need a more detailed clean?','Specialized crews with dedicated machinery for corporate flagships, private vessels, and sensitive finishes.':'For offices, yachts, showrooms and challenging spaces, we prepare a tailored quote before confirming the visit.',
    'Elevating Nordic residential sanctuaries and prime corporate spaces through meticulous, design-aware cleanliness across greater Tallinn.':'Professional cleaning in Tallinn for homes, offices and special spaces.','Complimentary rescheduling up to 36 hours prior to scheduled arrival.':'Changes or cancellations less than 36 hours before the visit may include a €20 fee.','Fair Care Guarantee':'Cancellation policy'
  };
  const tr={
    et:{'Professional cleaning for homes, offices and special spaces across Tallinn.':'Professionaalne koristus kodudele, kontoritele ja eriruumidele Tallinnas.','Personal coordination':'Isiklik koordineerimine','We review every request and confirm the details before your visit.':'Vaatame iga taotluse üle ja kinnitame detailid enne visiiti.','Cleaning supplies included':'Koristusvahendid hinna sees','We bring the essential supplies for standard cleaning.':'Toome tavakoristuseks vajalikud vahendid kaasa.','Clear scope':'Selge töömaht','Service, date and final price are confirmed before the visit.':'Teenuse, kuupäeva ja lõpliku hinna kinnitame enne visiiti.','Start planning':'Alusta planeerimist','Build your cleaning plan':'Koosta koristusplaan','Inspect Craft':'Vaata tulemust','A cleaner home.':'Puhtam kodu.','More time for life.':'Rohkem aega eluks.','CORE RESIDENTIAL SERVICES':'KODU KORISTUSTEENUSED','What would you like cleaned?':'Mida soovid koristada?','Regular cleaning':'Tavakoristus','Deep cleaning':'Suurpuhastus','Move-out & renovation':'Kolimis- ja remondijärgne koristus','Windows & textiles':'Aknad ja tekstiilid','Select & Estimate':'Vali ja arvuta','Need a more detailed clean?':'Vajad põhjalikumat koristust?','Build your cleaning plan.':'Koosta koristusplaan.','Space & Frequency':'Pind ja sagedus','Add-on Details':'Lisateenused','Schedule & Access':'Aeg ja ligipääs','Live Plan Summary':'Sinu plaani kokkuvõte','Continue to Confirmation':'Jätka kinnitamisega','Service Areas':'Teeninduspiirkonnad','Client Concierge':'Klienditugi','Service Standards':'Teenuse standardid','Policy Notice':'Oluline teave','Privacy Policy':'Privaatsuspoliitika','Terms of Service':'Tingimused','Cancellation policy':'Tühistamistingimused'},
    ru:{'Professional cleaning for homes, offices and special spaces across Tallinn.':'Профессиональная уборка домов, офисов и особых пространств в Таллине.','Personal coordination':'Личное сопровождение','We review every request and confirm the details before your visit.':'Мы проверяем каждую заявку и подтверждаем детали до визита.','Cleaning supplies included':'Средства включены','We bring the essential supplies for standard cleaning.':'Мы привозим необходимые средства для стандартной уборки.','Clear scope':'Понятный объём работ','Service, date and final price are confirmed before the visit.':'Услугу, дату и окончательную цену подтверждаем до визита.','Start planning':'Начать подбор','Build your cleaning plan':'Собрать план уборки','Inspect Craft':'Посмотреть результат','A cleaner home.':'Чистый дом.','More time for life.':'Больше времени для жизни.','CORE RESIDENTIAL SERVICES':'УСЛУГИ ДЛЯ ДОМА','What would you like cleaned?':'Что нужно убрать?','Regular cleaning':'Поддерживающая уборка','Deep cleaning':'Генеральная уборка','Move-out & renovation':'Уборка после переезда и ремонта','Windows & textiles':'Окна и текстиль','Select & Estimate':'Выбрать и рассчитать','Need a more detailed clean?':'Нужна более тщательная уборка?','Build your cleaning plan.':'Соберите план уборки.','Space & Frequency':'Помещение и частота','Add-on Details':'Дополнительные услуги','Schedule & Access':'Время и доступ','Live Plan Summary':'Ваш план уборки','Continue to Confirmation':'Перейти к подтверждению','Service Areas':'Районы обслуживания','Client Concierge':'Поддержка клиентов','Service Standards':'Стандарты сервиса','Policy Notice':'Важная информация','Privacy Policy':'Политика конфиденциальности','Terms of Service':'Условия сервиса','Cancellation policy':'Правила отмены'}
  };
  const replaceClean=()=>{const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),nodes=[];while(w.nextNode())nodes.push(w.currentNode);nodes.forEach(n=>{const v=n.nodeValue.trim();if(clean[v])n.nodeValue=n.nodeValue.replace(v,clean[v]);});};
  replaceClean();
  if (typeof translations !== 'undefined') {
    Object.assign(translations.EN, {heroBadge:'PROFESSIONAL CLEANING IN TALLINN',heroDescription:'Professional cleaning for homes, offices and special spaces across Tallinn.',trust1Title:'Personal coordination',trust1Desc:'We review every request and confirm the details before your visit.',trust2Title:'Cleaning supplies included',trust2Desc:'We bring the essential supplies for standard cleaning.',trust3Title:'Clear scope',trust3Desc:'Service, date and final price are confirmed before the visit.',transformEyebrow:'BEFORE & AFTER',transformTitle:'The difference is visible.',transformSub:'Compare the space before and after a detailed clean.',servicesSub:'Choose a service, tell us about your space and request a convenient time.',ctaPlan:'Build your cleaning plan',srvRegularTitle:'Regular cleaning',srvRegularFeat1:'Preferred cleaner when available',srvRegularFeat2:'Supplies included',srvDeepTitle:'Deep cleaning',srvDeepFeat1:'Limescale treatment',srvDeepFeat2:'Oven and extractor cleaning',srvMoveTitle:'Move-out & renovation',srvMoveDesc:'Detailed cleaning for moving or renovation. We confirm the scope before the visit.',srvMoveFeat1:'Clear service checklist',srvMoveFeat2:'Inside fixtures and cupboards',srvWinTitle:'Windows & textiles',srvWinFeat1:'Careful glass cleaning',srvWinFeat2:'Textile cleaning on request',badgeHandover:'MOVE-OUT READY',complexTitle:'Need a more detailed clean?',complexSub:'For offices, yachts, showrooms and challenging spaces, we prepare a tailored quote before confirming the visit.',compOfficeTitle:'Office cleaning',compShowTitle:'Showrooms & galleries',compYachtTitle:'Yachts & marine spaces',compYachtDesc:'Cleaning planned around the size, materials and access requirements of your vessel.',plannerTitle:'Build your cleaning plan.',plannerSub:'Choose your service and space details. We show an estimate and personally confirm the final price.',footerAbout:'Professional cleaning in Tallinn for homes, offices and special spaces.',footerPolicy:'Changes or cancellations less than 36 hours before the visit may include a €20 fee.'});
    Object.assign(translations.ET, {heroBadge:'PROFESSIONAALNE KORISTUS TALLINNAS',heroDescription:'Professionaalne koristus kodudele, kontoritele ja eriruumidele Tallinnas.',trust1Title:'Isiklik koordineerimine',trust1Desc:'Vaatame iga taotluse üle ja kinnitame detailid enne visiiti.',trust2Title:'Koristusvahendid hinna sees',trust2Desc:'Toome tavakoristuseks vajalikud vahendid kaasa.',trust3Title:'Selge töömaht',trust3Desc:'Teenuse, kuupäeva ja lõpliku hinna kinnitame enne visiiti.',transformEyebrow:'ENNE JA PÄRAST',transformTitle:'Erinevus on nähtav.',transformSub:'Võrdle ruumi enne ja pärast põhjalikku koristust.',servicesSub:'Vali teenus, kirjelda oma ruumi ja saada soovitud aja taotlus.',ctaPlan:'Koosta koristusplaan',srvRegularTitle:'Tavakoristus',srvRegularFeat1:'Võimalusel sama koristaja',srvRegularFeat2:'Koristusvahendid hinna sees',srvDeepTitle:'Suurpuhastus',srvDeepFeat1:'Katlakivi eemaldamine',srvDeepFeat2:'Ahju ja õhupuhasti puhastus',srvMoveTitle:'Kolimis- ja remondijärgne koristus',srvMoveDesc:'Põhjalik koristus kolimise või remondi järel. Kinnitame töömahu enne visiiti.',srvMoveFeat1:'Selge teenuse nimekiri',srvMoveFeat2:'Kapid ja sisepinnad',srvWinTitle:'Aknad ja tekstiilid',srvWinFeat1:'Hoolikas aknapesu',srvWinFeat2:'Tekstiilipuhastus soovi korral',badgeHandover:'KOLIMISEKS VALMIS',complexTitle:'Vajad põhjalikumat koristust?',complexSub:'Kontoritele, jahtidele, müügisalongidele ja keerukatele ruumidele koostame personaalse hinnapakkumise enne visiidi kinnitamist.',compOfficeTitle:'Kontorikoristus',compShowTitle:'Müügisalongid ja galeriid',compYachtTitle:'Jahid ja mereruumid',compYachtDesc:'Koristus vastavalt aluse suurusele, materjalidele ja ligipääsutingimustele.',plannerTitle:'Koosta koristusplaan.',plannerSub:'Vali teenus ja ruumi andmed. Näitame hinnangut ning kinnitame lõpliku hinna isiklikult.',footerAbout:'Professionaalne koristus Tallinnas kodudele, kontoritele ja eriruumidele.',footerPolicy:'Muudatused või tühistamine vähem kui 36 tundi enne visiiti võivad kaasa tuua €20 tasu.'});
    Object.assign(translations.RU, {heroBadge:'ПРОФЕССИОНАЛЬНАЯ УБОРКА В ТАЛЛИНЕ',heroDescription:'Профессиональная уборка домов, офисов и особых пространств в Таллине.',trust1Title:'Личное сопровождение',trust1Desc:'Мы проверяем каждую заявку и подтверждаем детали до визита.',trust2Title:'Средства включены',trust2Desc:'Мы привозим необходимые средства для стандартной уборки.',trust3Title:'Понятный объём работ',trust3Desc:'Услугу, дату и окончательную цену подтверждаем до визита.',transformEyebrow:'ДО И ПОСЛЕ',transformTitle:'Разница заметна.',transformSub:'Сравните пространство до и после тщательной уборки.',servicesSub:'Выберите услугу, расскажите о помещении и отправьте запрос на удобное время.',ctaPlan:'Собрать план уборки',srvRegularTitle:'Поддерживающая уборка',srvRegularFeat1:'Предпочтительный клинер при возможности',srvRegularFeat2:'Средства включены',srvDeepTitle:'Генеральная уборка',srvDeepFeat1:'Удаление известкового налёта',srvDeepFeat2:'Чистка духовки и вытяжки',srvMoveTitle:'Уборка после переезда и ремонта',srvMoveDesc:'Тщательная уборка после переезда или ремонта. Объём работ подтверждаем до визита.',srvMoveFeat1:'Понятный список работ',srvMoveFeat2:'Шкафы и внутренние поверхности',srvWinTitle:'Окна и текстиль',srvWinFeat1:'Бережная мойка окон',srvWinFeat2:'Химчистка текстиля по запросу',badgeHandover:'ГОТОВО К ПЕРЕЕЗДУ',complexTitle:'Нужна более тщательная уборка?',complexSub:'Для офисов, яхт, шоурумов и сложных помещений мы готовим индивидуальный расчёт до подтверждения визита.',compOfficeTitle:'Уборка офисов',compShowTitle:'Шоурумы и галереи',compYachtTitle:'Яхты и морские пространства',compYachtDesc:'Уборку планируем с учётом размера, материалов и условий доступа к судну.',plannerTitle:'Соберите план уборки.',plannerSub:'Выберите услугу и параметры помещения. Мы покажем ориентир и лично подтвердим итоговую цену.',footerAbout:'Профессиональная уборка в Таллине для домов, офисов и особых пространств.',footerPolicy:'Изменения или отмена менее чем за 36 часов до визита могут включать плату €20.'});
    Object.assign(translations.EN, {
      noPaymentReassurance:'Changes or cancellations less than 36 hours before the visit may include a €20 fee.',
      modalGuarantee:'We review your request and confirm availability, service details and final price before the visit.',
      successSub:'Thank you. We will review your request and contact you to confirm the details.'
    });
    Object.assign(translations.ET, {
      noPaymentReassurance:'Muudatused või tühistamine vähem kui 36 tundi enne visiiti võivad kaasa tuua €20 tasu.',
      modalGuarantee:'Vaatame taotluse üle ning kinnitame saadavuse, teenuse detailid ja lõpliku hinna enne visiiti.',
      successSub:'Täname! Vaatame taotluse üle ja võtame teiega detailide kinnitamiseks ühendust.'
    });
    Object.assign(translations.RU, {
      noPaymentReassurance:'Изменения или отмена менее чем за 36 часов до визита могут включать плату €20.',
      modalGuarantee:'Мы проверим заявку и подтвердим доступность, детали услуги и итоговую цену до визита.',
      successSub:'Спасибо! Мы рассмотрим заявку и свяжемся с вами, чтобы подтвердить детали.'
    });
  }
  const how=document.createElement('section');how.id='how-it-works';how.className='w-full bg-surface-container-low py-24';const faq=document.createElement('section');faq.id='faq';faq.className='w-full bg-surface py-24';document.querySelector('footer').before(how,faq);
  const extra={en:{a:'A SIMPLE WAY TO BOOK',b:'Clear service. Clear process.',s:[['01','Choose your service','Select a service and tell us what you need.'],['02','Share the details','Add space details, extras and a preferred time.'],['03','We confirm','We review availability and confirm the final price personally.']],f:'GOOD TO KNOW',g:'Clear answers before you book',q:[['What is included in regular cleaning?','Floors, accessible surfaces, kitchen and bathroom basics, mirrors, doors, handles, switches, cobwebs and rubbish removal.'],['How is the final price calculated?','The final price depends on the service, size and condition of the space, frequency and additional work. We confirm it before the visit.'],['Do you bring cleaning supplies?','Yes. Standard cleaning supplies are included unless you prefer us to use products already available at your home.'],['When is my request confirmed?','Your preferred date and time are a request until we confirm availability and the final price.']]},et:{a:'LIHTNE BRONEERIMINE',b:'Selge teenus. Selge protsess.',s:[['01','Vali teenus','Vali teenus ja kirjelda, mida vajad.'],['02','Lisa detailid','Lisa ruumi andmed, lisateenused ja sobiv aeg.'],['03','Kinnitame','Kontrollime saadavust ja kinnitame lõpliku hinna isiklikult.']],f:'HEA TEADA',g:'Selged vastused enne broneerimist',q:[['Mis sisaldub tavakoristuses?','Põrandad, ligipääsetavad pinnad, köögi ja vannitoa põhikoristus, peeglid, uksed, käepidemed, lülitid, ämblikuvõrgud ja prügi äravedu.'],['Kuidas lõplik hind kujuneb?','Hind sõltub teenusest, ruumi suurusest ja seisukorrast, sagedusest ning lisatöödest. Kinnitame selle enne visiiti.'],['Kas toote koristusvahendid kaasa?','Jah. Tavakoristuseks vajalikud vahendid on hinna sees, kui sa ei eelista kodus olevaid tooteid.'],['Millal taotlus kinnitatakse?','Valitud kuupäev ja aeg on soov, kuni kinnitame saadavuse ja lõpliku hinna.']]},ru:{a:'ПРОСТОЙ ПРОЦЕСС',b:'Понятная услуга. Понятный процесс.',s:[['01','Выберите услугу','Выберите услугу и расскажите, что нужно сделать.'],['02','Добавьте детали','Укажите параметры помещения, дополнения и удобное время.'],['03','Мы подтверждаем','Проверяем доступность и лично подтверждаем итоговую цену.']],f:'ВАЖНО ЗНАТЬ',g:'Понятные ответы до бронирования',q:[['Что входит в поддерживающую уборку?','Полы, доступные поверхности, базовая уборка кухни и ванной, зеркала, двери, ручки, выключатели, паутина и вынос мусора.'],['Как рассчитывается итоговая цена?','Цена зависит от услуги, размера и состояния помещения, частоты и дополнительных работ. Мы подтверждаем её до визита.'],['Вы привозите средства для уборки?','Да. Стандартные средства включены, если вы не предпочитаете использовать средства дома.'],['Когда заявка подтверждается?','Выбранные дата и время являются пожеланием, пока мы не подтвердим доступность и итоговую цену.']]}};
  const render=(lang)=>{const t=extra[lang];how.innerHTML=`<div class="max-w-7xl mx-auto px-6 lg:px-12"><div class="text-center max-w-2xl mx-auto mb-12"><p class="text-primary text-xs font-semibold tracking-[.16em] mb-3">${t.a}</p><h2 class="text-4xl md:text-5xl font-semibold tracking-tight">${t.b}</h2></div><div class="grid md:grid-cols-3 gap-5">${t.s.map(x=>`<article class="rounded-2xl bg-white border border-slate-200 p-7"><span class="text-primary font-semibold text-sm">${x[0]}</span><h3 class="mt-7 text-xl font-semibold">${x[1]}</h3><p class="mt-3 text-slate-600 leading-relaxed">${x[2]}</p></article>`).join('')}</div></div>`;faq.innerHTML=`<div class="max-w-4xl mx-auto px-6"><div class="text-center mb-12"><p class="text-primary text-xs font-semibold tracking-[.16em] mb-3">${t.f}</p><h2 class="text-4xl md:text-5xl font-semibold tracking-tight">${t.g}</h2></div><div class="space-y-3">${t.q.map((x,i)=>`<details class="group rounded-xl border border-slate-200 bg-white p-5" ${i?'':'open'}><summary class="cursor-pointer list-none font-semibold flex justify-between gap-5">${x[0]}<span class="text-primary">+</span></summary><p class="mt-3 text-slate-600 leading-relaxed">${x[1]}</p></details>`).join('')}</div></div>`;};
  const staticTerms={
    en:{save20:'-20% Save',save15:'-15% Save',save10:'-10% Save',standard:'Standard',district:'Tallinn Area',dimensions:'Space Dimensions',frequency:'Frequency Schedule',perVisit:'per cleaning',language:'Language:',areas:'Service Areas',concierge:'Client Concierge',standards:'Service Standards',policy:'Policy Notice',privacy:'Privacy Policy',terms:'Terms of Service',cancellation:'Cancellation policy',footer:'Professional cleaning in Tallinn for homes, offices and special spaces.',policyText:'Changes or cancellations less than 36 hours before the visit may include a €20 fee.'},
    et:{save20:'-20% soodustus',save15:'-15% soodustus',save10:'-10% soodustus',standard:'Tavahind',district:'Tallinna piirkond',dimensions:'Ruumi andmed',frequency:'Sagedus',perVisit:'ühe koristuse kohta',language:'Keel:',areas:'Teeninduspiirkonnad',concierge:'Klienditugi',standards:'Teenuse standardid',policy:'Oluline teave',privacy:'Privaatsuspoliitika',terms:'Tingimused',cancellation:'Tühistamistingimused',footer:'Professionaalne koristus Tallinnas kodudele, kontoritele ja eriruumidele.',policyText:'Muudatused või tühistamine vähem kui 36 tundi enne visiiti võivad kaasa tuua €20 tasu.'},
    ru:{save20:'Скидка -20%',save15:'Скидка -15%',save10:'Скидка -10%',standard:'Стандарт',district:'Район Таллина',dimensions:'Параметры помещения',frequency:'Периодичность',perVisit:'за одну уборку',language:'Язык:',areas:'Районы обслуживания',concierge:'Поддержка клиентов',standards:'Стандарты сервиса',policy:'Важная информация',privacy:'Политика конфиденциальности',terms:'Условия сервиса',cancellation:'Правила отмены',footer:'Профессиональная уборка в Таллине для домов, офисов и особых пространств.',policyText:'Изменения или отмена менее чем за 36 часов до визита могут включать плату €20.'}
  };
  const localizeStatic=lang=>{const lookup={};Object.values(staticTerms).forEach(dict=>Object.entries(dict).forEach(([key,value])=>lookup[value]=staticTerms[lang][key]));const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(node=>{const value=node.nodeValue.trim();if(lookup[value])node.nodeValue=node.nodeValue.replace(value,lookup[value]);});};
  const navigation={en:{planner:'Planner',services:'Services',how:'How it works',special:'Special projects',faq:'FAQ',start:'Start planning'},et:{planner:'Kalkulaator',services:'Teenused',how:'Kuidas see töötab',special:'Eriprojektid',faq:'KKK',start:'Alusta planeerimist'},ru:{planner:'Калькулятор',services:'Услуги',how:'Как это работает',special:'Спецпроекты',faq:'Вопросы и ответы',start:'Начать подбор'}};
  const updateNavigation=lang=>{const t=navigation[lang];const labels={planner:t.planner,services:t.services,'how-it-works':t.how,'special-projects':t.special,faq:t.faq};document.querySelectorAll('nav [data-path]').forEach(link=>{link.textContent=labels[link.dataset.path];});const start=[...document.querySelectorAll('header a')].find(link=>link.getAttribute('href')==='#planner-calc');if(start)start.textContent=t.start;};
  const setLanguage=lang=>{if(typeof applyLanguage==='function')applyLanguage(lang.toUpperCase());localizeStatic(lang);document.documentElement.lang=lang;updateNavigation(lang);render(lang);document.querySelectorAll('[data-language]').forEach(x=>x.classList.toggle('font-semibold',x.dataset.language===lang));};
  window.addEventListener('DOMContentLoaded',()=>{const remoteLogo=document.querySelector('header img[alt^="Brand logo"]');if(remoteLogo){const logo=document.createElement('span');logo.className='h-9 w-9 shrink-0 rounded-xl bg-primary text-white shadow-[0_5px_14px_rgba(0,104,95,.22)] flex items-center justify-center';logo.setAttribute('aria-label','PuhasPro logo');logo.innerHTML='<svg viewBox="0 0 28 28" class="w-6 h-6" aria-hidden="true"><path d="M7 21V7h7.2a5.1 5.1 0 0 1 0 10.2H11V21H7Zm4-7.3h3.1a1.8 1.8 0 0 0 0-3.5H11v3.5Z" fill="currentColor"/><path d="m20.6 5 .8 2.2 2.2.8-2.2.8-.8 2.2-.8-2.2-2.2-.8 2.2-.8.8-2.2Z" fill="#89f5e7"/></svg>';remoteLogo.replaceWith(logo);}const serviceLabel=document.querySelector('[data-i18n="catalogEyebrow"]');const specialLabel=document.querySelector('[data-i18n="complexEyebrow"]');if(serviceLabel)serviceLabel.closest('section').id='services';if(specialLabel)specialLabel.closest('section').id='special-projects';const targets={planner:'#planner-calc',services:'#services','how-it-works':'#how-it-works','special-projects':'#special-projects',faq:'#faq'};document.querySelectorAll('[data-path]').forEach(link=>{const target=targets[link.dataset.path];if(target)link.href=target;});const options=[...document.querySelectorAll('span')].filter(x=>['EN','ET','RU'].includes(x.textContent.trim()));options.forEach(x=>{const lang=x.textContent.trim().toLowerCase();x.dataset.language=lang;x.tabIndex=0;x.classList.add('cursor-pointer');x.addEventListener('click',()=>setLanguage(lang));x.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' ')setLanguage(lang);});});setLanguage('en');});
})();
